### ISSUE TITLE
dynamic config nodes

### ISSUE THREAD

**Issue by bruggerk** [elixir-no-nels/ehos-python#11]
Currently all nodes are configure as:

NUM_SLOTS = 1
NUM_SLOTS_TYPE_1 = 1
SLOT_TYPE_1 = cpus=100%
SLOT_TYPE_1_PARTITIONABLE = false

It would be better to have this reflect the available number of CPUs etc. 

Not sure if this is to be done by ehos or htcondor can do this

**Comment by oskarvid** [comment]
The current settings enable usage of multiple cores by a job, what is the
purpose of changing the settings to reflect the number of CPUs?

**Comment by bruggerk** [comment]
There are multiple reasons for this, but of the top of my head:

1. if a job can run on, or require, multiple cores have htcondor run the job on a node that meet these requirements 

2. having multiple jobs run on a single node.

3. better use of compute by having a mix of small and large nodes by directing jobs to the most suitable node.

**Comment by oskarvid** [comment]
The current settings enable the points you are listing.
