### ISSUE TITLE
Investigate HTCondor + data transfer penalties

### ISSUE THREAD

**Issue by bruggerk** [elixir-no-nels/ehos-python#9]
Investigate the following questions:

1. Is is possible to submit a job from an external compute and share data with the master + slave nodes

2. What are the data sharing mechanisms used in HTCondor

3. How are binary dependencies resolved (if they are)? Eg: try and run a dynamical linked binary on a client. If a binary differs between master and slave, which one is being run?

4. How long does it take to transfer a large dataset between nodes

**Comment by oskarvid** [comment]
5. Run a job with "program --version" and save the output to a text file?

**Comment by bruggerk** [comment]
Some notes on this:

1. This works like a charm

2. HTcondor copies the data off, runs the software, and returns the files generated. If transferring files these have to be specified in the job file, whereas any file generated is returned

3. HTcondor will first try and run a binary placed on the slave, however if the the slave binary differs from the one on the submission host this one will be used instead. If not present on the slave this will revert to transferring the binary as well
If the binary is dynamically linked to a library not installed on the node this will fail. (Used bespoke c-programs to test this).


4. Transfer rates follow normal transfer rates:
Given a 10% overhead these are the transfer times in seconds(for future reference ):

Network|1 Mbit|10 Mbit|100 Mbit|1 Gbit|10 Gbit|100 Gbit
-----------|--------|----------|------------|--------|---------|------------
1 GB|	8200.192|	820.0192|	82.00192|	8.008|	0.8008|	0.08008
4 GB|	32800.768|	3280.0768|	328.00768|	32.032|	3.2032|	0.32032
50 GB|	410009.6|	41000.96|	4100.096|	400.4|	40.04|	4.004
100 GB|	820019.2|	82001.92|	8200.192|	800.8|	80.08|	8.008
200 GB|	1640038.4|	164003.84|	16400.384|	1601.6|	160.16|	16.016

**Comment by bruggerk** [comment]
Real life example

Ran BWA on an exome dataset from 1KG:

input files: 7.4GB (compressed)
output: 24 GB ( uncompresed)
The job ran in parallel on a 8 core vm, with the reference on the compute node

Average for 10 runs (Friday afternoon 19.10.2018):

Input transfer time: 99 sec
Runtime: ~1337 sec
Output transfer time: 156 sec

Running the same job on laptop (same nr of cores, but SSD):
Input transfer time: 0 sec
Runtime: 1157 sec
Output transfer time: 0 sec



**Notes:**

Loads of silly business with this one as the analysis fills up the disk. Mounted /var/lib/condor/execute onto an external volume in the end as I could not find the correct setting to point to somewhere else.

# Getting the stats
condor_history -l 13.0
JobCurrentStartDate = 1539935953
JobCurrentStartExecutingDate = 1539935983
JobCurrentStartTransferOutputDate = 1539936166
JobFinishedHookDone = 1539936174
